Add noqa statements.
We can now ignore given errors (even specific instances
of a given error) using noqa statements.

This required a significant change in how docstrings
were parsed, hence the Docstring class.

__Example usage:__

    def has_many_errors(missing_arg):
        """This docstring has many problems, and we ignore them all.

        We can ignore all instances of a problem by putting the noqa
        statement on the global level, without any arguments, as below:

        # noqa: I402

        That ignores excess raises.  We can also ignore specific
        problems at the global level.  For example, we can ignore the
        missing parameter, missing_arg, which isn't in the function definition.

        # noqa: I101 missing_arg

        Args:
            excess_arg: The noqa statment at the end of this line
                will allow us to ignore this excess one. # noqa: I102

        Raises:
            ZeroDivisionError: Ignored by the global noqa.

        """
        missing_arg / 0